# Generated by Django 4.2.7 on 2025-12-03 20:17

import certificates.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import events.models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('speakers', models.JSONField(blank=True, default=list)),
                ('timezone', models.CharField(default='Asia/Manila', max_length=50)),
                ('category', models.CharField(choices=[('HCDC', 'HCDC Wide Event'), ('department', 'Department Event'), ('outside', 'Outside Event')], default='HCDC', max_length=20)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('departmental_details', markdownx.models.MarkdownxField(blank=True, help_text='Markdown supported for departmental events', null=True)),
                ('theme', models.CharField(default='Professional Blue', max_length=50)),
                ('cover_image', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('is_paid_event', models.BooleanField(default=False)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('code_prefix', models.CharField(blank=True, max_length=16)),
                ('registration_url', models.URLField(blank=True)),
                ('event_qr_code', models.TextField(blank=True)),
                ('certificate_template_image', models.TextField(blank=True, help_text='Upload a landscape-oriented certificate template (PNG, JPG, JPEG, GIF, BMP, or WEBP). Any size is supported.', validators=[certificates.validators.validate_landscape_certificate, certificates.validators.validate_certificate_image_format])),
                ('certificate_coordinates', models.JSONField(blank=True, default=events.models.default_certificate_coordinates)),
                ('certificate_sample_text', models.JSONField(blank=True, default=events.models.default_certificate_sample_text)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.TextField(blank=True)),
                ('qr_code_value', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('barcode_image', models.TextField(blank=True)),
                ('is_present', models.BooleanField(default=False)),
                ('has_evaluated', models.BooleanField(default=False)),
                ('is_eligible_for_certificate', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='events.eventregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(blank=True, help_text='Generated certificate file', max_length=500, null=True, upload_to='certificates/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_emailed', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='events.eventregistration')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
